/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author IGNITER
 */
public class MedInfoView extends javax.swing.JPanel {

    /**
     * Creates new form anadirPane
     */
    public MedInfoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        sobredosis = new javax.swing.JLabel();
        informacion = new javax.swing.JLabel();
        compuesto = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        RestriccionesEmbarazo = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        ReaccionesAdversas = new javax.swing.JLabel();
        Contraindicaciones = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        InteraccionesMedicamentosas = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        LeyendasProteccion = new javax.swing.JLabel();
        PrecaucionesGrales = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        precaucionesCancerigenas = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sobredosis.setText("Manifestaciones y manejo de sobredosis");
        jPanel3.add(sobredosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 270, 20));

        informacion.setText("Información del Medicamento");
        jPanel3.add(informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        compuesto.setText("Compuesto");
        jPanel3.add(compuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel3.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 40, 40));

        jScrollPane2.setViewportView(jTextPane1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 161, -1));

        RestriccionesEmbarazo.setText("Restricciones de uso durante el embarazo");
        jPanel3.add(RestriccionesEmbarazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 230, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 270, 90));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane5.setViewportView(jTextArea3);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 270, 90));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane6.setViewportView(jTextArea4);

        jPanel3.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 270, 90));

        ReaccionesAdversas.setText("Reacciones Adversas");
        jPanel3.add(ReaccionesAdversas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 150, -1));

        Contraindicaciones.setText("Contraindicaciones");
        jPanel3.add(Contraindicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 160, 20));

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane7.setViewportView(jTextArea5);

        jPanel3.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 270, 90));

        InteraccionesMedicamentosas.setText("Interacciones Medicamentosas");
        jPanel3.add(InteraccionesMedicamentosas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 180, 20));

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane8.setViewportView(jTextArea6);

        jPanel3.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 270, 90));

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jScrollPane9.setViewportView(jTextArea7);

        jPanel3.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 270, 90));

        LeyendasProteccion.setText("Leyendas de Proteccion");
        jPanel3.add(LeyendasProteccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 140, 20));

        PrecaucionesGrales.setText("Precauciones Generales");
        jPanel3.add(PrecaucionesGrales, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 140, 20));

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jScrollPane10.setViewportView(jTextArea8);

        jPanel3.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 270, 90));

        precaucionesCancerigenas.setText("Precauciones en relacion con efectos cancerígenos");
        jPanel3.add(precaucionesCancerigenas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 270, 20));

        jTextArea9.setColumns(20);
        jTextArea9.setRows(5);
        jScrollPane11.setViewportView(jTextArea9);

        jPanel3.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 270, 90));

        jScrollPane3.setViewportView(jTextPane2);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 161, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contraindicaciones;
    private javax.swing.JLabel InteraccionesMedicamentosas;
    private javax.swing.JLabel LeyendasProteccion;
    private javax.swing.JLabel PrecaucionesGrales;
    private javax.swing.JLabel ReaccionesAdversas;
    private javax.swing.JLabel RestriccionesEmbarazo;
    private javax.swing.JLabel compuesto;
    private javax.swing.JButton exit;
    private javax.swing.JLabel informacion;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JLabel precaucionesCancerigenas;
    private javax.swing.JLabel sobredosis;
    // End of variables declaration//GEN-END:variables
}
