/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author IGNITER
 */
public class MedInfoView extends javax.swing.JPanel {
    private MainView parent;
    
    /**
     * Creates new form anadirPane
     */
    public MedInfoView(MainView parent) {
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        informacion = new javax.swing.JLabel();
        compuesto = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCompound = new javax.swing.JTextPane();
        Contraindicaciones = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtDescrp = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtName = new javax.swing.JTextPane();

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        informacion.setText("Información del Medicamento");
        jPanel3.add(informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        compuesto.setText("Compuesto");
        jPanel3.add(compuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        btnExit.setText("X");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel3.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 40, 40));

        txtCompound.setEditable(false);
        jScrollPane2.setViewportView(txtCompound);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 161, -1));

        Contraindicaciones.setText("Descripcion");
        jPanel3.add(Contraindicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 160, 20));

        txtDescrp.setEditable(false);
        txtDescrp.setColumns(20);
        txtDescrp.setLineWrap(true);
        txtDescrp.setRows(5);
        txtDescrp.setTabSize(4);
        jScrollPane7.setViewportView(txtDescrp);

        jPanel3.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 270, 90));

        txtName.setEditable(false);
        jScrollPane3.setViewportView(txtName);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 161, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        
        parent.changeToWeekView();
    }//GEN-LAST:event_btnExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contraindicaciones;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel compuesto;
    private javax.swing.JLabel informacion;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextPane txtCompound;
    private javax.swing.JTextArea txtDescrp;
    private javax.swing.JTextPane txtName;
    // End of variables declaration//GEN-END:variables
}
