/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;


/**
 *
 * @author IGNITER
 */
public class WeekView extends javax.swing.JPanel {
       
    private int month;
    private int year;
    

    
    public WeekView() {
       initComponents();
      initStyles();
      
    }
    
     private void initStyles() {
        
        domingo.putClientProperty("FlatLaf.style", "font:bold $h3.regular.font");
        domingo.setForeground(Color.black);
        
        lunes.putClientProperty("FlatLaf.style", "font:bold $h3.regular.font");
        lunes.setForeground(Color.black);
        
        martes.putClientProperty("FlatLaf.style", "font:bold $h3.regular.font");
        martes.setForeground(Color.black);
        
        miercoles.putClientProperty("FlatLaf.style", "font:bold $h3.regular.font");
        miercoles.setForeground(Color.black);
        
        jueves.putClientProperty("FlatLaf.style", "font:bold $h3.regular.font");
        jueves.setForeground(Color.black);
        
        viernes.putClientProperty("FlatLaf.style", "font:bold $h3.regular.font");
        viernes.setForeground(Color.black);
        
        sabado.putClientProperty("FlatLaf.style", "font:bold $h3.regular.font");
        sabado.setForeground(Color.black);

       listaLunes.putClientProperty("FlatLaf.style", "font:bold $h4.regular.font");
        listaLunes.setForeground(Color.black);
        
        listaMartes.putClientProperty("FlatLaf.style", "font:bold $h4.regular.font");
        listaMartes.setForeground(Color.black);
        
        listaMier.putClientProperty("FlatLaf.style", "font:bold $h4.regular.font");
        listaMier.setForeground(Color.black);
        
        listaJueves.putClientProperty("FlatLaf.style", "font:bold $h4.regular.font");
        listaJueves.setForeground(Color.black);
        
        listaViernes.putClientProperty("FlatLaf.style", "font:bold $h4.regular.font");
        listaViernes.setForeground(Color.black);
        
        listaSabado.putClientProperty("FlatLaf.style", "font:bold $h4.regular.font");
            listaSabado.setForeground(Color.black);
            
        listaDom.putClientProperty("FlatLaf.style", "font:bold $h4.regular.font");
        listaDom.setForeground(Color.black);
    }
     
     
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lunes = new javax.swing.JLabel();
        domingo = new javax.swing.JLabel();
        miercoles = new javax.swing.JLabel();
        martes = new javax.swing.JLabel();
        jueves = new javax.swing.JLabel();
        sabado = new javax.swing.JLabel();
        viernes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaSabado = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        listaDom = new javax.swing.JList<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        listaLunes = new javax.swing.JList<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        listaMartes = new javax.swing.JList<>();
        jScrollPane12 = new javax.swing.JScrollPane();
        listaMier = new javax.swing.JList<>();
        jScrollPane13 = new javax.swing.JScrollPane();
        listaJueves = new javax.swing.JList<>();
        jScrollPane14 = new javax.swing.JScrollPane();
        listaViernes = new javax.swing.JList<>();

        setBackground(getBackground());
        setPreferredSize(new java.awt.Dimension(730, 410));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lunes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lunes.setText("Lunes");
        lunes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 100, 70));

        domingo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        domingo.setText("Domingo");
        domingo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(domingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 70));

        miercoles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        miercoles.setText("Miércoles");
        miercoles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(miercoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 100, 70));

        martes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        martes.setText("Martes");
        martes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(martes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 100, 70));

        jueves.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jueves.setText("Jueves");
        jueves.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jueves, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 100, 70));

        sabado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sabado.setText("Sabado");
        sabado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(sabado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 100, 70));

        viernes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viernes.setText("Viernes");
        viernes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(viernes, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 100, 70));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setToolTipText("");
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        listaSabado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaSabado);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 100, 310));

        jScrollPane9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane9.setToolTipText("");
        jScrollPane9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        listaDom.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(listaDom);

        add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 100, 310));

        jScrollPane10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane10.setToolTipText("");
        jScrollPane10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        listaLunes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(listaLunes);

        add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 100, 310));

        jScrollPane11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane11.setToolTipText("");
        jScrollPane11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        listaMartes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane11.setViewportView(listaMartes);

        add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 100, 310));

        jScrollPane12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane12.setToolTipText("");
        jScrollPane12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        listaMier.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane12.setViewportView(listaMier);

        add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 100, 310));

        jScrollPane13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane13.setToolTipText("");
        jScrollPane13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        listaJueves.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane13.setViewportView(listaJueves);

        add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 100, 310));

        jScrollPane14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane14.setToolTipText("");
        jScrollPane14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        listaViernes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane14.setViewportView(listaViernes);

        add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 100, 310));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel domingo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel jueves;
    private javax.swing.JList<String> listaDom;
    private javax.swing.JList<String> listaJueves;
    private javax.swing.JList<String> listaLunes;
    private javax.swing.JList<String> listaMartes;
    private javax.swing.JList<String> listaMier;
    private javax.swing.JList<String> listaSabado;
    private javax.swing.JList<String> listaViernes;
    private javax.swing.JLabel lunes;
    private javax.swing.JLabel martes;
    private javax.swing.JLabel miercoles;
    private javax.swing.JLabel sabado;
    private javax.swing.JLabel viernes;
    // End of variables declaration//GEN-END:variables
}
